
var XLSX = (function(XLSX) {
	
	XLSX.version = '0.17.0';

	var DENSE = null;
	var DIF_XL = true;

	@import "jszip.js"
	
	@import "02_codepage.js"
	@import "04_base64.js"
	@import "05_buf.js"
	@import "09_types.js"
	@import "10_ssf.js"
	@import "11_ssfutils.js"
	@import "18_cfb.js"
	@import "19_fsutils.js"
	@import "20_jsutils.js"
	@import "21_ziputils.js"
	@import "22_xmlutils.js"
	@import "23_binutils.js"
	@import "24_hoppers.js"
	@import "25_cellutils.js"
	@import "27_csfutils.js"
	@import "28_binstructs.js"
	@import "29_xlsenum.js"
	@import "30_ctype.js"
	@import "31_rels.js"
	@import "32_odmanrdf.js"
	@import "33_coreprops.js"
	@import "34_extprops.js"
	@import "35_custprops.js"
	@import "36_xlsprops.js"
	@import "38_xlstypes.js"
	@import "39_xlsbiff.js"
	@import "40_harb.js"
	@import "42_sstxml.js"
	@import "43_sstbin.js"
	@import "44_offcrypto.js"
	@import "45_rtf.js"
	@import "46_stycommon.js"
	@import "47_styxml.js"
	@import "48_stybin.js"
	@import "49_theme.js"
	@import "50_styxls.js"
	@import "52_calcchain.js"
	@import "53_externlink.js"
	@import "54_drawing.js"
	@import "55_vml.js"
	@import "56_cmntcommon.js"
	@import "57_cmntxml.js"
	@import "58_cmntbin.js"
	@import "59_vba.js"
	@import "60_macrovba.js"
	@import "61_fcommon.js"
	@import "62_fxls.js"
	@import "63_fbin.js"
	@import "64_ftab.js"
	@import "65_fods.js"
	@import "66_wscommon.js"
	@import "67_wsxml.js"
	@import "68_wsbin.js"
	@import "69_chartxml.js"
	@import "70_csheet.js"
	@import "71_wbcommon.js"
	@import "72_wbxml.js"
	@import "73_wbbin.js"
	@import "74_xmlbin.js"
	@import "75_xlml.js"
	@import "76_xls.js"
	@import "77_parsetab.js"
	@import "78_writebiff.js"
	@import "79_html.js"
	@import "80_parseods.js"
	@import "81_writeods.js"
	@import "82_sheeter.js"
	@import "84_defaults.js"
	@import "85_parsezip.js"
	@import "86_writezip.js"
	@import "87_read.js"
	@import "88_write.js"
	@import "90_utils.js"
	@import "95_api.js"
	@import "98_exports.js"

	return XLSX;

})({});

module.exports = XLSX;
